;;; .user-lisp-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from modules/cfg-core.el

(register-definition-prefixes "modules/cfg-core" '("browse-url" "my/" "package-"))


;;; Generated autoloads from modules/cfg-ui.el

(register-definition-prefixes "modules/cfg-ui" '("my/"))


;;; Generated autoloads from modules/cfg-windows.el

(register-definition-prefixes "modules/cfg-windows" '("my/split-and-follow-" "toggle-"))


;;; Generated autoloads from sv-kalender.el

(register-definition-prefixes "sv-kalender" '("sv-"))

;;; End of scraped data

(provide '.user-lisp-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; .user-lisp-autoloads.el ends here
