#!/usr/bin/env sh

# scripting addition
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa && sh ~/.config/yabai/scripts/update_script_add.sh"

# focus next window when quitting program
yabai -m signal --add event=window_destroyed \
      active=yes \
      action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse &> /dev/null || yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id) &> /dev/null"

# focus next window when minimizing window
yabai -m signal --add event=window_minimized \
      active=yes \
      action="if \$(yabai -m query --windows --window \$YABAI_WINDOW_ID | jq -r '.\"is-floating\"'); then yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse &> /dev/null || yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id) &> /dev/null; fi"

# trigger window_focus event in sketchybar when window is focused
yabai -m signal --add event=window_focused \
      action="sketchybar --trigger window_focus &> /dev/null"

# clean up empty spaces with no windows on them
yabai -m signal --add event=space_changed \
      action="sh ~/.config/yabai/scripts/destroy_empty_spaces.sh && sketchybar --trigger space_change"

# defaults
yabai -m config                                          \
                layout                      bsp          \
                split_ratio                 0.50         \
                split_type                  auto         \
                auto_balance                off          \
                external_bar                main:0:25    \
                                                         \
                top_padding                 20           \
                bottom_padding              20           \
                left_padding                20           \
                right_padding               20           \
                window_gap                  20           \
                                                         \
                window_placement            second_child \
                window_shadow               off          \
                                                         \

# rules
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="System Settings" app="^System Settings$" manage=off
yabai -m rule --add label="App Store" app="^App Store$" manage=off
yabai -m rule --add label="Activity Monitor" app="^Activity Monitor$" manage=off
yabai -m rule --add label="Calculator" app="^Calculator$" manage=off
yabai -m rule --add label="Dictionary" app="^Dictionary$" manage=off
yabai -m rule --add label="Software Update" title="^Software Update$" manage=off
yabai -m rule --add label="About This Mac" app="^System Information$" manage=off
yabai -m rule --add label="Raindrop" app="^Raindrop.io$" manage=off
yabai -m rule --add label="Bitwarden" app="^Bitwarden$" manage=off
yabai -m rule --add label="OVPN" app="^OVPN$" manage=off
yabai -m rule --add label="Installer" app="^Installer$" manage=off
yabai -m rule --add label="Spotify" app="^Spotify$" manage=off
yabai -m rule --add label="Proton Mail Bridge" app="^Proton Mail Bridge$" manage=off
yabai -m rule --add label="MacVim" app="^MacVim$" manage=off
yabai -m rule --add label="mpv" app="^mpv$" manage=off
yabai -m rule --add label="Teams" app="^Microsoft Teams (work or school)$" manage=off
yabai -m rule --add label="Alfred" app="^Alfred Preferences$" manage=off
yabai -m rule --add label="Font Book" app="^Font Book$" manage=off
yabai -m rule --add label="Karabiner" app="^Karabiner-Elements$" manage=off
yabai -m rule --add label="Anki" app="^Anki$" title="(Add|Browse|Preview)" manage=off
yabai -m rule --add label="AltTab" app="^AltTab$" title="(General|Controls|Appearance|Policies|Blacklists|About|Acknowledgements)" manage=off
yabai -m rule --add label="Terminal" app="^WezTerm$" manage=off

# workarounds for hiding window decorations successfully
yabai -m rule --add app="^qutebrowser$" role="AXWindow" subrole="AXDialog" manage=on
yabai -m rule --add app="sioyek$" role="AXWindow" subrole="AXDialog" manage=on
