#!/bin/sh

xhost +

# set fallback cursor
xsetroot -cursor_name left_ptr

# set keyboard repeat rate
xset r rate 300 50

# disable access control
xhost +SI:localuser:$USER

# auto-start
gnome-settings-daemon &
tlp &
syncthing --no-browser &
kmonad &
redshift &
nm-applet &
pasystray &

# launch emacs
exec i3
