#!/bin/sh

# Set fallback cursor.
xsetroot -cursor_name left_ptr

# Set keyboard repeat rate.
xset r rate 300 50

# If Emacs is started in server mode, `emacsclient` is a convenient way to
# edit files in place (used by e.g. `git commit`).
export VISUAL=emacsclient
export EDITOR="$VISUAL"

# Disable access control
xhost +SI localuser $USER

tlp &
syncthing -no-browser &
nm-applet &
pasystray &

# Finally launch emacs.
exec dbus-launch --exit-with-session emacs
