#!/bin/sh

# set fallback cursor
xsetroot -cursor_name left_ptr

# set keyboard repeat rate
xset r rate 300 50

# set suspend settings
xset dpms 120 300

# disable access control
xhost +SI:localuser:$USER

# auto-start
gnome-settings-daemon &
tlp &
syncthing --no-browser &
kmonad &
xbanish &
redshift &
nm-applet &
alttab &

# launch wm
exec i3
