# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-z
bind-key C-z send-prefix

# Enable mouse
set -g mouse

# Status bar conf
set -g window-status-current-style bg=red,fg=white  # Active window color
set -g window-status-style bg=yellow                # Inactive window color
set -g status-right '#H'

# reload config file
bind r source-file ~/.config/tmux/tmux.conf

# Pane navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Resize
bind-key -r H resize-pane -L 5
bind-key -r J resize-pane -D 5
bind-key -r K resize-pane -U 5
bind-key -r L resize-pane -R 5

# Kill all other panes
bind-key k kill-pane -a

# Increase status bar message time
set-option -g display-time 2000
set-option -g display-panes-time 2000

# Increase max number of lines in history
set-option -g history-limit 50000

# Lock session after 60 min
set-option -g lock-after-time 3600

# Turn on escape sequence passthrough
set -g allow-passthrough on
