#!/usr/bin/env sh

PLUGIN_DIR="$HOME/.config/sketchybar/plugins"
ITEM_DIR="$HOME/.config/sketchybar/items"

PADDING=5
LABEL_FONT="JetBrains Mono"

bar=(
    height=25
    blur_radius=0
    padding_left=0
    padding_right=$PADDING
    color=0xff000000
    position=bottom
    sticky=on
    display=main
)

sketchybar --bar "${bar[@]}"

defaults=(
    updates=when_shown
    drawing=on
    label.font="$LABEL_FONT:Regular:14.0"
    label.padding_left=$PADDING
    label.padding_right=$PADDING
    label.color=0xffFFFFFF
)

sketchybar --default "${defaults[@]}"

# left
source "$ITEM_DIR/spaces.sh"
#source "$ITEM_DIR/front_app.sh"

# right
source "$ITEM_DIR/date_and_time.sh"
source "$ITEM_DIR/network.sh"
source "$ITEM_DIR/battery.sh"
#source "$ITEM_DIR/memory.sh"
#source "$ITEM_DIR/cpu.sh"
source "$ITEM_DIR/vpn.sh"

sketchybar --hotload on

# initializing
sketchybar --update

echo "sketchybar configuration loaded..."
