inactive-opacity = 0.95;
active-opacity = 1.00;
backend = "glx";
use-damage = true;
vsync = true;
fading = true;
fade-in-step = 0.06;
fade-out-step = 0.06;

blur:
{
    method = "box";
    size = 7;
};

# Semi-transparent
blur-background = true;

# Use fixed blur strength rather than adjusting according to window opacity
blur-background-fixed = true;
