[colors]
background                = #000000
foreground                = #cecece
foreground-alt            = #bdc0c7
red                       = #a54242
grey                      = #424858

[bar/bar1]
height                    = 15pt
bottom                    = true
background                = ${colors.background}
foreground                = ${colors.foreground}
separator                 = |
separator-foreground      = ${colors.grey}
font-0                    = "Terminus:size=13;3"
font-1                    = "Symbols Nerd Font Mono:size=9;3"
cursor-click              = pointer
enable-ipc                = true

modules-left              = xworkspaces xwindow i3
modules-right             = caffeinate mpd cpu battery date tray

[settings]
screenchange-reload       = true

[module/xwindow]
type                      = internal/xwindow

[module/tray]
type                      = internal/tray
tray-size                 = 50%:15pt

[module/mpd]
type                      = internal/mpd
host                      = 127.0.0.1
port                      = 6600
label-song                =  %artist% - %title%

[module/i3]
type                      = internal/i3
format                    = <label-mode>

[module/xworkspaces]
type                      = internal/xworkspaces

label-active              = %name%
label-active-padding      = 1
label-active-background   = ${colors.grey}
label-active-foreground   = ${colors.foreground}

label-occupied            = %name%
label-occupied-padding    = 1
label-occupied-foreground = ${colors.foreground-alt}

label-empty               = %name%
label-empty-padding       = 1
label-empty-foreground    = ${colors.grey}

label-urgent              = %name%
label-urgent-padding      = 1
label-urgent-foreground   = ${colors.red}

[module/battery]
type                      = internal/battery
low-at                    = 40
full-at                   = 95
battery                   = BAT0
adapter                   = AC
time-format               = %H:%M

format-charging           = <label-charging>
format-low                = <label-low>

label-full                =
label-charging            = BAT %percentage%% [CHR]
label-discharging         = BAT %percentage%% %time%
label-low                 = BAT %{F#A54242}%percentage%%%{F-} %time%

[module/cpu]
type                      = internal/cpu
interval                  = 4
format-prefix             = %{A1:~/scripts/cpu_popup:}CPU %{A1}
format                    = %{A1:~/scripts/cpu_popup:}<label>%{A1}
label                     = %percentage:3%%

[module/date]
type                      = internal/date
date                      = %F %a
time                      = %H:%M
format                    = <label>
label                     = %date% %{F#66b032}%time%%{F-}
label-foreground          = ${colors.foreground}

; show whether caffeinate (keep system from suspending) is running
[module/caffeinate]
type                      = custom/script
exec                      = ~/scripts/check_caffeinate
format-foreground         = #ffa500
interval                  = 5
click-left                = exec pkill caffeinate
