[colors]
background = #000000
foreground = #cecece
red = #a54242
grey = #707880

[bar/bar1]
width = 100%
height = 15pt
bottom = true

background = ${colors.background}
foreground = ${colors.foreground}

module-margin = 1

separator = |
separator-foreground = ${colors.grey}

font-0 = "monospace:size=10;4"
font-1 = "Symbols Nerd Font Mono:size=10;4"

modules-left = xworkspaces i3
modules-center = mpd
modules-right = caffeinate cpu battery date tray

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true

[module/tray]
type = internal/tray
tray-spacing = 10px
tray-padding = 1px
tray-size = 50%:15pt

[module/mpd]
type = internal/mpd
host = 127.0.0.1
port = 6600
label-song =  %artist% - %title%

[module/i3]
type = internal/i3
format = <label-mode>

[module/xworkspaces]
type = internal/xworkspaces

label-active = [ %name% ]
label-active-padding = 1

label-occupied = %name%
label-occupied-padding = 1
label-occupied-foreground = ${colors.grey}

label-empty = %name%
label-empty-padding = 1
label-empty-foreground = ${colors.grey}

label-urgent = %name%
label-urgent-padding = 1
label-urgent-foreground = ${colors.red}

[module/battery]
type = internal/battery
low-at = 40
full-at = 95
battery = BAT0
adapter = AC
time-format = %H:%M

format-charging = <label-charging>
format-low = <label-low>

label-full = BAT full
label-charging = BAT %percentage%% [CHR]
label-discharging = BAT %percentage%% %time%
label-low = BAT %{F#A54242}%percentage%%%{F-} %time%

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = %{A1:~/scripts/cpu_popup:}CPU %{A1}
format = %{A1:~/scripts/cpu_popup:}<label>%{A1}
label = %percentage:3%%

[module/date]
type = internal/date
interval = 1
date = %a %d %b %R
format = <label>
label = %date%
label-foreground = ${colors.foreground}

; show whether caffeinate (keep system from suspending) is running
[module/caffeinate]
type = custom/script
exec = ~/scripts/check_caffeinate
interval = 2
click-left = exec pkill caffeinate

[settings]
screenchange-reload = true
