# Split panes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# Reload config file
bind r source-file ~/.tmux.conf

# Enable mouse control (clickable windows, panes, resizable panes)
set -g mouse on

# Don't rename windows automatically
set-option -g allow-rename off

# Hide date and time in status bar
set -g status-right '#H'
