# Open scrollback in emacs
map f1 launch --stdin-source=@screen_scrollback --stdin-add-formatting --type=overlay /home/najjt/scripts/emacs_pager.sh

tab_bar_edge top
tab_bar_style custom
tab_bar_margin_width 2
tab_bar_margin_height 5 0
tab_title_template "{fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{index}: {title}"

# Dark
foreground              #d3d7cf
background              #2e3436
active_tab_foreground   #d3d7cf
active_tab_background   #2e3436
active_tab_font_style   normal
inactive_tab_foreground #d3d7cf
inactive_tab_background #222222
tab_bar_background      #222222
tab_bar_margin_color    #222222

# Light
#foreground              #2e3436
#background              #eeeeec
#active_tab_foreground   #2e3436
#active_tab_background   #eeeeec
#active_tab_font_style   normal
#inactive_tab_foreground #2e3436
#inactive_tab_background #cccccc
#tab_bar_background      #cccccc
#tab_bar_margin_color    #cccccc
