# Open scrollback in emacs
map f1 launch --stdin-source=@screen_scrollback --stdin-add-formatting --type=overlay /home/najjt/scripts/emacs_pager.sh

# Font
font_family Noto Sans Mono
font_size 11.0

# Tab bar
tab_bar_edge top
tab_bar_style custom
tab_bar_margin_width 2
tab_bar_margin_height 5 0
tab_title_template "{fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{index}: {title}"

# Dark colors
foreground              #d3d7cf
background              #222222
active_tab_foreground   #d3d7cf
active_tab_background   #222222
active_tab_font_style   normal
inactive_tab_foreground #d3d7cf
inactive_tab_background #2e3436
tab_bar_background      #2e3436
tab_bar_margin_color    #2e3436
