# Open scrollback in emacs
map f1 launch --stdin-source=@screen_scrollback --stdin-add-formatting --type=overlay /home/najjt/scripts/emacs_pager.sh

# Font
font_family Noto Sans Mono
font_size 11.0

# Tab bar
tab_bar_edge top
tab_bar_style       custom
tab_separator       ""
tab_title_template  " {index} {title} "
